version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: second_hand_market
      POSTGRES_PASSWORD: 123456
      TZ: UTC
    volumes:
      - second_hand_market-pg-local:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  second_hand_market-pg-local: