spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: havntsetupyet@gmail.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/second_hand_market
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver