spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: havntsetupyet@gmail.com
    password: your_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:localhost}:5432/second_hand_market
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

alioss:
  endpoint: oss-us-west-1.aliyuncs.com
  access-key-id: LTAI5tDYKyUTznYwcET1YNVG
  access-key-secret: HMx2Jv6HQa2C69i6cI0POljaY4i8mV
  bucket-name: 2-hand-market